
extends:
    - airbnb-base

rules: 
    # http://eslint.cn/docs/rules/#best-practices

    # http://eslint.cn/docs/rules/#stylistic-issues
    linebreak-style: 0

    # http://eslint.cn/docs/rules/#strict-mode
    # strict: 0
