root: true

extends:
    - airbnb-base

# override airbnb-base setting
env:
    es6: false
    jasmine: true

parserOptions:
    ecmaVersion: 5
    sourceType: script
    ecmaFeatures:
        impliedStrict: false
        experimentalObjectRestSpread: false

rules: 
    # http://eslint.cn/docs/rules/#best-practices

    # http://eslint.cn/docs/rules/#stylistic-issues
    linebreak-style: 0
    padded-blocks: 0
    func-names: 0
    spaced-comment:
        - 2
        - always
        - {exceptions: ['/', '-', '+', '=']}

    # http://eslint.cn/docs/rules/#strict-mode
    strict: 
        - 1
        - function

    # http://eslint.cn/docs/rules/#variables
    no-use-before-define: 0

    # http://eslint.cn/docs/rules/#ecmascript-6
    arrow-body-style: 0
    arrow-parens: 0
    arrow-spacing: 0
    constructor-super: 0
    generator-star-spacing: 0
    no-class-assign: 0
    no-confusing-arrow: 0
    no-const-assign: 0
    no-dupe-class-members: 0
    no-duplicate-imports: 0
    no-new-symbol: 0
    no-restricted-imports: 0
    no-this-before-super: 0
    no-useless-computed-key: 0
    no-useless-constructor: 0
    no-useless-rename: 0
    no-var: 0
    object-shorthand: 0
    prefer-arrow-callback: 0
    prefer-const: 0
    prefer-destructuring: 0
    prefer-numeric-literals: 0
    prefer-rest-params: 0
    prefer-spread: 0
    prefer-template: 0
    require-yield: 0
    rest-spread-spacing: 0
    sort-imports: 0
    symbol-description: 0
    template-curly-spacing: 0
    yield-star-spacing: 0
    
