root: true

globals:
    angular: true

extends:
    - airbnb-base

plugins:
    - angular

# override airbnb-base setting
parserOptions:
    ecmaVersion: 5
    sourceType: script
    ecmaFeatures:
        impliedStrict: false
        experimentalObjectRestSpread: false

rules: 
    # http://eslint.cn/docs/rules/#best-practices

    # http://eslint.cn/docs/rules/#stylistic-issues
    linebreak-style: 0
    padded-blocks: 0
    func-names: 0

    # http://eslint.cn/docs/rules/#strict-mode
    strict: 
        - 1
        - function

    #--------------------------------
    # plugin:angualr
    #--------------------------------
    # Possible Errors
    angular/module-getter: 2
    angular/module-setter: 2
    angular/no-private-call: 2

    # Best Practices
    angular/component-limit: 2
    angular/controller-as-route: 2
    angular/controller-as-vm: 2
    angular/controller-as: 2
    angular/deferred: 2
    angular/di-unused: 2
    angular/directive-restrict: 2
    angular/empty-controller: 2
    angular/no-controller: 2
    angular/no-inline-template: 2
    angular/no-run-logic: 2
    angular/no-services: 2
    angular/on-watch: 2
    angular/prefer-component: 2

    # Deprecated Angular Features
    angular/no-cookiestore: 2
    angular/no-directive-replace: 2
    angular/no-http-callback: 2

    # Naming
    angular/component-name: 2
    angular/constant-name: 2
    angular/controller-name: 2
    angular/directive-name: 2
    angular/factory-name: 2
    angular/file-name: 
        - 2
        - nameStyle: dash
          typeSeparator: dot
          ignoreTypeSuffix: true
          componentTypeMappings:
              factory: service
              provider: service
              service: service
    angular/filter-name: 2
    angular/module-name: 0
    angular/provider-name: 2
    angular/service-name: 2
    angular/value-name: 2

    # Conventions
    angular/di-order: 2
    angular/di: 2
    angular/dumb-inject: 2
    angular/function-type: 2
    angular/module-dependency-order: 2
    angular/no-service-method: 2
    angular/one-dependency-per-line: 2
    angular/rest-service: 2
    angular/watchers-execution: 2

    # Angular Wrappers
    angular/angularelement: 2
    angular/definedundefined: 2
    angular/document-service: 2
    angular/foreach: 2
    angular/interval-service: 2
    angular/json-functions: 2
    angular/log: 2
    angular/no-angular-mock: 2
    angular/no-jquery-angularelement: 2
    angular/timeout-service: 2
    angular/typecheck-array: 2
    angular/typecheck-date: 2
    angular/typecheck-function: 2
    angular/typecheck-number: 2
    angular/typecheck-object: 2
    angular/typecheck-string: 2
    angular/window-service: 2

    # Misspelling
    angular/on-destroy: 2
